ALTER TABLE disenos_archivos ADD COLUMN IF NOT EXISTS es_nuevo TINYINT(1) DEFAULT 1;
ALTER TABLE disenos_archivos ADD COLUMN IF NOT EXISTS visto_en DATETIME DEFAULT NULL;
ALTER TABLE disenos_archivos ADD COLUMN IF NOT EXISTS descargado_en DATETIME DEFAULT NULL;
ALTER TABLE disenos_archivos ADD COLUMN IF NOT EXISTS eliminado_en DATETIME DEFAULT NULL;

ALTER TABLE configuracion ADD COLUMN IF NOT EXISTS alertas_diseno_admin TINYINT(1) DEFAULT 0;
